### ISSUE TITLE
Proposals to improve

### ISSUE THREAD

**Issue by ilyar** [kdzwinel/CSS-Diff#14]
# Proposals to improve

- [ ] Add options:
 - [ ] Show color: `rgb`|`hex`
 - [ ] Show vendor prefixes: `yes`|`no`
- [ ] Compare params CSS of two HTML elements for example:
```css
ElemFoo {
  padding: 1px;
}

ElemBar {
  padding: 1px 2px;
}

diff(ElemFoo ElemBar) {
  padding-left: 2px;
  padding-right: 2px;
}

diff(ElemBar ElemFoo) {
  padding-left: 1px;
  padding-right: 1px;
}
```
